- name: Add the worker
  community.general.docker_swarm:
    state: join
    advertise_addr: swarm-workers
    join_token: "{{ hostvars['swarm-master']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: ['swarm-master:2377']